// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbWGdQ4xxE5dvlV9rXoYL_rc1P4P1yecQ',
    appId: '1:796522565005:web:a76345f37d0249896701c4',
    messagingSenderId: '796522565005',
    projectId: 'graduationproject-fc610',
    authDomain: 'graduationproject-fc610.firebaseapp.com',
    storageBucket: 'graduationproject-fc610.firebasestorage.app',
    measurementId: 'G-4ZCMRC9BM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4l1PyHnzLXKZnxtW-ReAIlNpi8M-DznE',
    appId: '1:796522565005:android:8158acd3523d7b856701c4',
    messagingSenderId: '796522565005',
    projectId: 'graduationproject-fc610',
    storageBucket: 'graduationproject-fc610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWm7jKFmByPn2pAbdtgngKr0SHfuC9ypA',
    appId: '1:796522565005:ios:751160ceabbca54c6701c4',
    messagingSenderId: '796522565005',
    projectId: 'graduationproject-fc610',
    storageBucket: 'graduationproject-fc610.firebasestorage.app',
    iosBundleId: 'com.buildagon.fluentify',
  );
}
